---
title: "nova"
author: "Qing Xu"
date: "November 12, 2017"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(haven)
library(readxl)
library(janitor)
library(knitr)
library(hexbin)
library(plotly)
library(ggridges)
noaa<- read_csv("nynoaadat.zip") %>%
       group_by(id)

```

```{r}
noaa<- separate(noaa,date, into = c("year", "month","day"), sep = "-")
  noaa<- noaa%<%
    group_by(year)
noaa$tmax<- as.numeric(noaa$tmax)
hist<- ggplot(noaa, aes(x = tmax, fill = year)) + 
  geom_histogram(alpha= 0.8)

ggplotly(hist)

```


```{r}
hexplot = filter(noaa, !is.na(tmax))%>%
  filter(!is.na(tmin))%>%
  mutate(tmax = as.numeric(tmax))%>%
  mutate(tmin = as.numeric(tmin))%>%
ggplot(aes(tmin, tmax)) +
  geom_hex()+
   labs(
    title = "Tmax against tmin",
    x = "tmin",
    y = "tmax",
    caption = "ny_noaa_data_year"
  ) + 
  theme_classic()
ggplotly(hexplot)
```

```{r}
ny_noaa_data_snowfall =
  filter(noaa, snow > 0 & snow < 100)%>%
  ggplot(aes(x = year, y = snow, fill = year, color = year)) + 
  geom_violin()+ 
  labs(
    title = "Snowfall Distribution of each year",
    x = "Snowfall Distribution",
    y = "Year",
    caption = "Data from ny_noaa_data"
  ) + 
  theme_classic() + 
  theme(legend.position = "bottom")
ggplotly(ny_noaa_data_snowfall)
```

 