---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(shiny)
library(httr)
library(jsonlite)
library(zipcode)
library(maps)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/9w7m-hzhe.json"

nyc_inspections = get_all_inspections(url) %>%
  bind_rows() 

```

```{r}
boros = nyc_inspections %>% distinct(boro) %>% pull()

# selectInput widget
selectInput("boro_choice", label = h3("Select boro"),
            choices = boros, selected = "Manhattan")
```


Row
-----------------------------------------------------------------------

### Chart A

```{r}


```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B
```{r}
nyc_inspections$score<- as.numeric(nyc_inspections$score)
nyc_inspections %>% 
  filter(grade %in% c("A","B","C"), boro != "Missing") %>% 
  plot_ly(x = ~grade, y = ~score, type = "box",
          alpha = 0.5, 
          color = ~grade) %>%
  layout(title = "Score distribution in grades")

```

### Chart C

```{r}
bar_plot<- nyc_inspections %>% 
  filter(grade %in% c("A","B","C"), boro != "Missing") %>% 
  mutate(boro = fct_infreq(boro)) %>%
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar()+
  labs(title = "Grades of restaurants in each boro")

ggplotly(bar_plot)

```

